### PR TITLE
Geometric stiffness matrix formulation for truss topopt 

### LINKED ISSUE #25: Truss geometric stiffness matrix unit tests
Currently, the geometric stiffness matrix construction (used for buckling constraint)  returns incorrect results. I will try to debug that and add a few tests to compare against some textbook examples.

### PR DESCRIPTION
**Pull request by yijiangh**
### Summary

This PR includes supports for buckling modeling of truss structures. It contains geometric stiffness matrix formulations, related tests, and detailed documentation with clear literature pointers. It closes #25.

**Highlights**:
1. Geometric stiffness matrix formulation for truss elements with verifiable reference sources. 
2. `test/truss_topopt_problems/test_geometric_stiffness_matrix.jl` includes an example of using the geometric stiffness matrix and a hand-made forward Euler integration to simulate large displacement.
3. `test/truss_topopt_problems/test_buckling.jl` includes examples to check that the ground mesh is stable and the compliance-optimized truss is not stable by using the geometric stiffness matrix.

**Minor changes**:
1. Removed `examples/benchmark` in favor of our latest [WCSMO21 benchmarks](https://github.com/JuliaTopOpt/TopOpt.jl_WCSMO21)
 
### What type of change is this?

- [ ] Bug fix in a **backwards-compatible** manner.
- [x] New feature in a **backwards-compatible** manner.
- [ ] Breaking change: bug fix or new feature that involve incompatible API changes.
- [ ] Other (e.g. doc update, configuration, etc)

### Checklist

- [x] I ran all tests on my computer and it's all green (i.e. `] test`).
- [x] I have added tests that prove my fix is effective or that my feature works.
- [x] I have added necessary documentation (if appropriate)

### CODE REVIEW

File: src/TrussTopOptProblems/buckling.jl [hunk 1]
```diff
@@ -1,79 +1,142 @@
...
+# Arguments
+`end_vert_u, end_vert_v` = vectors for nodal coordinate
+
+# Outputs
+`R` = (ndim x ndim) global_from_local transformation matrix
+    Note that this matrix has its columns as axes
+    So should be used as R*K*R' instead of R'*K*R as indicated in
+    https://people.duke.edu/~hpgavin/cee421/truss-finite-def.pdf
+"""
+function compute_local_axes(end_vert_u, end_vert_v)
```
Comment (mohamed82008) [inline src/TrussTopOptProblems/buckling.jl:17]: This might need some explanation. Let's talk about it today.

File: src/TrussTopOptProblems/buckling.jl [hunk 2]
```diff
@@ -86,19 +149,36 @@ function buckling(problem::TrussProblem{xdim, T}, ginfo, einfo; u=undef) where {
...
+            Ferrite.assemble!(assembler, global_dofs, Kσ_e)
         else
-            Ferrite.assemble!(assembler, global_dofs, Kσs[i])
+            px = vars[varind[i]]
+            # if PENALTY_BEFORE_INTERPOLATION
+            # px = density(penalty(vars[varind[i]]), xmin)
+            # else
+                # px = penalty(density(vars[varind[i]], xmin))
+            # end
+            Kσ_e = px * Kσ_e
```
Comment (mohamed82008) [inline src/TrussTopOptProblems/buckling.jl:174]: I am not sure if we should do this for trusses unless we are going for 0-1 designs. If the thickness is optimized then the Ksigma comes from the stress and we shouldn't multiply by the density in assembly here.

**Review by mohamed82008 — APPROVED** [review]
